services:
  api:
    build: .
    image: black_friday_sales:latest
    container_name: black_friday_sales_api
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - PORT=8080
    # Override the default entrypoint to ensure we run the specific file 'serve:app'
    # 'uv run' ensures it executes within the managed environment
    command: ["uv", "run", "uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8080"]

  dashboard:
    image: black_friday_sales:latest
    container_name: black_friday_sales_eda
    depends_on:
      - api
    ports:
      - "8050:8050"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    # Override entrypoint to run the Python script instead of the API
    command: ["uv", "run", "python", "eda.py"]